config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "messages#index"
  resources :groups do
    resources :messages, only: [:create]
    collection do
      get  :ajax_user_list
    end
    member do
      get :ajax_add_users
    end
  end
  resources :messages, exept: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_many :messages, dependent: :destroy
  has_many :user_groups
  has_many :users, through: :user_groups
  accepts_nested_attributes_for :user_groups
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :nickname, presence: true

  has_many :messages
  has_many :user_groups
  has_many :groups, through: :user_groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname] )
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:edit, :update]
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    redirect_to root_path, notice: 'グループが作成されました' if Group.create(group_params)
  end

  def edit
  end

  def update
    redirect_to root_path, notice: 'グループが作成されました' if @group.update(group_params)
  end

  def ajax_user_list
    @users = User.where('nickname LIKE(?)', "%#{ params[:q] }%")
  end

  def ajax_add_users
    @group.users << User.find(params[:id])
    redirect_to root_path
  end

  private
  def find_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:group_id].present?
      @group = Group.find(params[:group_id])
      @messages = @group.messages
    else
      @group = current_user.groups.first
      @messages = @group.messages
    end
    @groups = current_user.groups
    @message = Message.new
  end

  def create
    if Message.create(group_params)
      group = Group.find(params[:group_id])
      @messages = group.messages
    else
      redirect_to root_path, notice: 'メッセージの送信に失敗しました'
    end
  end

  private
  def group_params
    params.require(:message).permit(:body, :group_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/groups/_ajax_user_list.html.haml
- if @users.present?
  - @users.each do |user|
    %li{id: "user_#{user.id}"}
      = user.nickname
      = button_tag '追加', type: 'button', class: "ajax_user_list", 'data-user-id': user.id, 'data-user-name': user.nickname

app/views/groups/_form.haml
= form_for @group do |f|
  %form#new_chat_group.new_chat_group{ "accept-charset" => "UTF-8", :action => "/chat_groups", :method => "post" }
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group-form__input', placeholder: "グループ名を入力してください", type: "text"
        = f.hidden_field :group_id, value: @group.id
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{ :for => "chat_group_チャットメンバーを追加" } チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{ :placeholder => "追加したいユーザー名を入力してください", :type => "text" }/
        %ul#user-search-result
          = render partial: "ajax_user_list", locals: { group: @group, f: f }
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        #chat-group-users
          - unless @group.id.nil?
            - @group.users.each do |user|
              .chat-group-user.clearfix{ id: "chat-group-user-#{ user.id }" }
                %input{ type: 'hidden', name: 'group[user_ids][]', value: user.id }
                %p.chat-group-user__name
                  = user.nickname
                %button{ class: 'user_list_remove', type: "button", "data-user-id": user.id }
                  削除
          - else
            #chat-group-user-current-user.chat-group-user.clearfix
              %p.chat-group-user__name
                = current_user.nickname
              %input{ type: 'hidden', name: 'group[user_ids][]', value: current_user.id }
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        %input.chat-group-form__action-btn{ "data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save" }/

app/views/groups/_group.html.haml
- @groups.each do |group|
  %li.group
    = link_to root_path( group_id: group.id ), class: 'group__link' do
      .group__name
        %B
          #{ group.name }
      .group__first-message
        = group.messages.last.body if group.messages.any?

app/views/groups/_side_bar.html.haml
.side-bar
  .side-bar__user
    .side-bar__user__name.left.bold
      = current_user.nickname
    .user-actions.right
      = link_to edit_user_registration_path, class: "user-actions__action edit" do
        %i.fa.fa-pencil-square-o
      = link_to new_group_path, class: "user-actions__action setting" do
        %i.fa.fa-cog
  %ul.side-bar__groups
    = render partial: 'groups/group'

app/views/groups/ajax_user_list.js.erb
$("#user-search-result").html("<%= escape_javascript(render partial: 'ajax_user_list', locals: { users: @users, group: @group } ) %>");

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial:'form'

app/views/layouts/_flash.html.haml
%ul.flash.position-absolute
  - flash.each do |key, value|
    %li{ class: "#{key}"}
      = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace2
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/messages/_message.html.haml
%li.message
  .message__information
    %span.name.dark-blue.bold
      = message.user.nickname
    %span.date.gray
      = message.created_at.strftime('%Y/%m/%d %H:%M:%S')
  %p.message__body
    = message.body

app/views/messages/create.js.erb
$(".text-field").val(""); // 入力フォームを空欄にする処理
$(".position-relative").html("<%= j(render @messages) %>");

app/views/messages/index.html.haml
.chat
  = render partial: 'groups/side_bar'
  .chat-group
    .group
      .group__informations.left
        .name
        = @group.name
        .members.gray
          Members:
          - @group.users.each do |user|
            %span.member-name
              = user.nickname
      .right
        = link_to 'Edit', edit_group_path(@group), class: 'edit'
    %ul.messages.position-relative
      = render partial: 'layouts/flash'
      = render @messages
    = form_for [@group, @message], html: { class: 'chat__form' }, remote: true  do |f|
      = f.text_field :body, class: 'text-field', placeholder: 'Type a message'
      = f.hidden_field :group_id, value: @group.id
      = f.submit '送信', class: 'submit'